# Generated by Django 4.2.7 on 2024-03-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.IntegerField(default=True),
        ),
    ]
